replicaCount: 1

image:
  repository: himanshadewmin/go-web-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "24467094244"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernets.io/ingress.class: nginx
    # kubernets.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: ImplementationSpecific